[build]
   publish = "dist/futuryweb"
   command = "npm run build"
[redirects]
  # Example of a redirect rule
  from = "/old-path"
  to = "/new-path"
  status = 301  # Permanent redirect

[headers]
  # Example of setting custom headers for specific paths
  "/.netlify/*" = [
    "X-Content-Type-Options: nosniff",
    "X-Robots-Tag: noindex, nofollow",
  ]
